version: '3'

tasks:
  deploy-node:
    internal: true
    cmds:
      - >
        talosctl gen config homelab https://192.168.0.41:6443
        --force
        --with-secrets secrets.yaml
        --config-patch @patches/all.yaml
        --config-patch-control-plane @patches/cp.yaml
        --config-patch-worker @patches/worker.yaml
        --output-dir out
      - talosctl machineconfig patch {{.TYPE}}.yaml --patch @nodes/{{.NODE}}.yaml -o out/final-{{.NODE}}.yaml
  generate:
    cmds:
      - for: [cp-1, cp-2, cp-3]
        task: deploy-node
        vars:
          TYPE: controlplane
          NODE: "{{.ITEM}}"
      - for: [w-1, w-2, w-3]
        task: deploy-node
        vars:
          TYPE: worker
          NODE: "{{.ITEM}}"
  join:
    requires:
      vars:
        - IP
        - NODE
    cmds:
      - task: generate
      - talosctl apply-config --insecure -n {{.IP}} --file out/final-{{.NODE}}.yaml
